<p style="text-align: center;"><span style="font-size: small;"><img src="https://media.discordapp.net/attachments/626252895892799518/633103847165919253/elfbot-ngaa.png" alt="" /></span></p>
<p style="text-align: center;"><span style="font-size: medium;"><strong>Hotkeys de Combo NTO Hard</strong></span></p>
<p style="text-align: center;"><span style="font-size: medium;">&nbsp;</span></p>
<p style="text-align: center;"><span style="font-size: small;"><img src="https://media.discordapp.net/attachments/629369600269877248/630509014370746379/sasuke.png" alt="" /></span></p>
<p style="text-align: center;"><span style="font-size: small;"><strong><img class="emoji" src="https://discordapp.com/assets/df0fba917be2ad5fc7939019465de627.svg" alt=":round_pushpin:" width="17" height="17" />&nbsp;Sasuke&nbsp;</strong><strong><img class="emoji" src="https://discordapp.com/assets/c6b26ba81f44b0c43697852e1e1d1420.svg" alt=":white_check_mark:" width="16" height="16" /></strong></span></p>
<address style="text-align: center;"><span style="font-size: small;">auto 250 listas 'Combo Sasuke' | isattacking say Kagutsuchi Amaterasu | isattacking say Toshishita Kirin | isattacking say Susano Arch| isattacking say Indora no Ya</span></address><address style="text-align: center;">&nbsp;</address><address style="text-align: center;"><span style="font-size: small;"><img src="https://media.discordapp.net/attachments/629369600269877248/630509056611844097/sakura.png" alt="" /></span></address>
<p style="text-align: center;"><span style="font-size: small;"><strong><img class="emoji" src="https://discordapp.com/assets/df0fba917be2ad5fc7939019465de627.svg" alt=":round_pushpin:" width="17" height="17" />Sakura&nbsp;<img class="emoji" src="https://discordapp.com/assets/c6b26ba81f44b0c43697852e1e1d1420.svg" alt=":white_check_mark:" width="16" height="16" /></strong></span></p>
<address style="text-align: center;"><span style="font-size: small;">auto 250 listas 'Combo Sakura' | isattacking say Daichiwari | isattacking say Oukasho | isattacking say Shingurupanchi | isattacking say Haruchugeki</span></address><address style="text-align: center;">&nbsp;</address><address style="text-align: center;"><span style="font-size: small;"><img src="https://media.discordapp.net/attachments/629369600269877248/630509458862374913/lee.png" alt="" /></span></address>
<p style="text-align: center;"><span style="font-size: small;"><strong><img class="emoji" src="https://discordapp.com/assets/df0fba917be2ad5fc7939019465de627.svg" alt=":round_pushpin:" width="17" height="17" />Rock Lee&nbsp;<img class="emoji" src="https://discordapp.com/assets/c6b26ba81f44b0c43697852e1e1d1420.svg" alt=":white_check_mark:" width="16" height="16" /></strong></span></p>
<address style="text-align: center;"><span style="font-size: small;">auto 250 listas 'Combo Lee' | isattacking say Final Entry | isattacking say Kage Buyo | isattacking say Asa Kujaku | isattacking say Taijutsu Furie Sequence</span></address><address style="text-align: center;">&nbsp;</address><address style="text-align: center;"><span style="font-size: small;"><img src="https://media.discordapp.net/attachments/629369600269877248/630509750508978252/neji.png" alt="" /></span></address>
<p style="text-align: center;"><span style="font-size: small;"><strong><img class="emoji" src="https://discordapp.com/assets/df0fba917be2ad5fc7939019465de627.svg" alt=":round_pushpin:" width="17" height="17" />Neji&nbsp;<img class="emoji" src="https://discordapp.com/assets/c6b26ba81f44b0c43697852e1e1d1420.svg" alt=":white_check_mark:" width="16" height="16" /></strong></span></p>
<address style="text-align: center;"><span style="font-size: small;">auto 250 listas 'Combo Neji' | isattacking say Hakke Rokujuyon Sho | isattacking say Hakke Kuhekisho | isattacking say Hakke Kusho | isattacking say Hakke Hyakunijuuhachishou</span></address><address style="text-align: center;">&nbsp;</address><address style="text-align: center;"><span style="font-size: small;"><img src="https://media.discordapp.net/attachments/629369600269877248/630510148661542923/tenten.png" alt="" /></span></address>
<p style="text-align: center;"><span style="font-size: small;"><strong><img class="emoji" src="https://discordapp.com/assets/df0fba917be2ad5fc7939019465de627.svg" alt=":round_pushpin:" width="17" height="17" />Tenten&nbsp;<img class="emoji" src="https://discordapp.com/assets/c6b26ba81f44b0c43697852e1e1d1420.svg" alt=":white_check_mark:" width="16" height="16" /></strong></span></p>
<address style="text-align: center;"><span style="font-size: small;">auto 250 listas 'Combo Tenten' | isattacking say Bansho Kaze no Maki | isattacking say Sugu Tensasai | isattacking say Soshoryu | isattacking say Shobu</span></address><address style="text-align: center;">&nbsp;</address><address style="text-align: center;"><span style="font-size: small;"><img src="https://media.discordapp.net/attachments/629369600269877248/630510397350346783/gaara.png" alt="" /></span></address>
<p style="text-align: center;"><span style="font-size: small;"><strong><img class="emoji" src="https://discordapp.com/assets/df0fba917be2ad5fc7939019465de627.svg" alt=":round_pushpin:" width="17" height="17" />Gaara<img class="emoji" src="https://discordapp.com/assets/c6b26ba81f44b0c43697852e1e1d1420.svg" alt=":white_check_mark:" width="16" height="16" /></strong></span></p>
<address style="text-align: center;"><span style="font-size: small;">auto 250 listas 'Combo Gaara' | isattacking say Sabaku Demon | isattacking say Sabaku Catch | isattacking say Suna Shigure | isattacking say Sabaku Sotaiso</span></address><address style="text-align: center;">&nbsp;</address><address style="text-align: center;"><span style="font-size: small;"><img src="https://media.discordapp.net/attachments/629369600269877248/630510829070057472/kiba.png" alt="" /></span></address>
<p style="text-align: center;"><span style="font-size: small;"><strong><img class="emoji" src="https://discordapp.com/assets/df0fba917be2ad5fc7939019465de627.svg" alt=":round_pushpin:" width="17" height="17" />Kiba&nbsp;<img class="emoji" src="https://discordapp.com/assets/c6b26ba81f44b0c43697852e1e1d1420.svg" alt=":white_check_mark:" width="16" height="16" /></strong></span></p>
<address style="text-align: center;"><span style="font-size: small;">auto 250 listas 'Combo Kiba' | isattacking say Dynamic Garoga | isattacking say Dynamic Entory | isattacking say Jinju Kongo Santoro | isattacking say Garoga</span></address><address style="text-align: center;">&nbsp;</address><address style="text-align: center;"><span style="font-size: small;"><img src="https://media.discordapp.net/attachments/629369600269877248/630511115717050388/shikamaru.png" alt="" /></span></address>
<p style="text-align: center;"><span style="font-size: small;"><strong><img class="emoji" src="https://discordapp.com/assets/df0fba917be2ad5fc7939019465de627.svg" alt=":round_pushpin:" width="17" height="17" />Shikamaru&nbsp;<img class="emoji" src="https://discordapp.com/assets/c6b26ba81f44b0c43697852e1e1d1420.svg" alt=":white_check_mark:" width="16" height="16" /></strong></span></p>
<address style="text-align: center;"><span style="font-size: small;">auto 250 listas 'Combo Shikamaru' | isattacking say Kageyose No Jutsu | isattacking say Kage Tsukigame No Jutsu | isattacking say Nikudan Yoyo | isattacking say Kage Nui No Jutsu</span></address><address style="text-align: center;">&nbsp;</address><address style="text-align: center;"><span style="font-size: small;"><img src="https://media.discordapp.net/attachments/629369600269877248/630511538335383592/chouji.png" alt="" /></span></address>
<p style="text-align: center;"><span style="font-size: small;"><strong><img class="emoji" src="https://discordapp.com/assets/df0fba917be2ad5fc7939019465de627.svg" alt=":round_pushpin:" width="17" height="17" />Chouji&nbsp;<img class="emoji" src="https://discordapp.com/assets/c6b26ba81f44b0c43697852e1e1d1420.svg" alt=":white_check_mark:" width="16" height="16" /></strong></span></p>
<address style="text-align: center;"><span style="font-size: small;">auto 250 listas 'Combo Chouji' | isattacking say Cho Baika no Jutsu | isattacking say Choharite | isattacking say Potchari Daibu | isattacking say Bunbun Baika</span></address><address style="text-align: center;">&nbsp;</address><address style="text-align: center;"><span style="font-size: small;"><img style="width: 65px; height: 66px;" src="https://media.discordapp.net/attachments/629369600269877248/640544288157204491/hashirama.png" alt="" /></span></address>
<p style="text-align: center;"><span style="font-size: small;"><strong><img class="emoji" src="https://discordapp.com/assets/df0fba917be2ad5fc7939019465de627.svg" alt=":round_pushpin:" width="17" height="17" />Hashirama&nbsp;<img class="emoji" src="https://discordapp.com/assets/c6b26ba81f44b0c43697852e1e1d1420.svg" alt=":white_check_mark:" width="16" height="16" /></strong></span></p>
<address style="text-align: center;"><span style="font-size: small;">auto 250 listas 'Combo Hashirama' | isattacking say Jukai Kotan | isattacking say Hijutsu Jukai Kotan | isattacking say Gosoju no Jutsu | isattacking say Mokuton Mokuryuy</span></address><address style="text-align: center;">&nbsp;</address><address style="text-align: center;"><span style="font-size: small;"><img style="width: 65px; height: 66px;" src="https://media.discordapp.net/attachments/629369600269877248/640544351067439108/tobirama.png" alt="" /></span></address>
<p style="text-align: center;"><span style="font-size: small;"><strong><img class="emoji" src="https://discordapp.com/assets/df0fba917be2ad5fc7939019465de627.svg" alt=":round_pushpin:" width="17" height="17" />Tobirama&nbsp;<img class="emoji" src="https://discordapp.com/assets/c6b26ba81f44b0c43697852e1e1d1420.svg" alt=":white_check_mark:" width="16" height="16" /></strong></span></p>
<address style="text-align: center;"><span style="font-size: small;">auto 250 listas 'Combo Tobirama' | isattacking say Suiton Suishoha | isattacking say Suiton Teppodama | isattacking say Suiton Suiryu Kobaku | isattacking say Suiton Suidanha</span></address><address style="text-align: center;">&nbsp;</address><address style="text-align: center;"><span style="font-size: small;"><img style="width: 65px; height: 66px;" src="https://media.discordapp.net/attachments/629369600269877248/640544393702408202/sarutobi.png" alt="" /></span></address>
<p style="text-align: center;"><span style="font-size: small;"><strong><img class="emoji" src="https://discordapp.com/assets/df0fba917be2ad5fc7939019465de627.svg" alt=":round_pushpin:" width="17" height="17" />Sarutobi&nbsp;<img class="emoji" src="https://discordapp.com/assets/c6b26ba81f44b0c43697852e1e1d1420.svg" alt=":white_check_mark:" width="16" height="16" /></strong></span></p>
<address style="text-align: center;"><span style="font-size: small;">auto 250 listas 'Combo Sarutobi' | isattacking say Shiki Death Fujin | isattacking say Dragon Flame Projectile | isattacking say Fuuma Weapon Attack | isattacking say Enma Atack</span></address><address style="text-align: center;">&nbsp;</address><address style="text-align: center;"><span style="font-size: small;"><img style="width: 65px; height: 66px;" src="https://media.discordapp.net/attachments/629369600269877248/640544485511659520/mianto.png" alt="" /></span></address>
<p style="text-align: center;"><span style="font-size: small;"><strong><strong><img class="emoji" src="https://discordapp.com/assets/df0fba917be2ad5fc7939019465de627.svg" alt=":round_pushpin:" width="17" height="17" />Minato&nbsp;<img class="emoji" src="https://discordapp.com/assets/c6b26ba81f44b0c43697852e1e1d1420.svg" alt=":white_check_mark:" width="16" height="16" /></strong></strong></span></p>
<address style="text-align: center;"><span style="font-size: small;">auto 250 listas 'Combo Minato' | isattacking say Hiraishin Furie Rasengan | isattacking say Shiki Fujin | isattacking say Matagama Fujin | isattacking say Ni No Dan Rasengan</span></address><address style="text-align: center;">&nbsp;</address><address style="text-align: center;"><span style="font-size: small;"><img style="width: 65px; height: 66px;" src="https://media.discordapp.net/attachments/629369600269877248/640544560073670676/tsunade.png" alt="" /></span></address>
<p style="text-align: center;"><span style="font-size: small;"><strong><img class="emoji" src="https://discordapp.com/assets/df0fba917be2ad5fc7939019465de627.svg" alt=":round_pushpin:" width="17" height="17" />Tsunade&nbsp;<img class="emoji" src="https://discordapp.com/assets/c6b26ba81f44b0c43697852e1e1d1420.svg" alt=":white_check_mark:" width="16" height="16" /></strong></span></p>
<address style="text-align: center;"><span style="font-size: small;">auto 250 listas 'Combo Tsunade' | isattacking say Oukashou Tsutenkyaku | isattacking say Oukashou Jiware | isattacking say Kryuchi Panchi | isattacking say Nokkuauto no buro</span></address><address style="text-align: center;">&nbsp;</address><address style="text-align: center;"><span style="font-size: small;"><img style="width: 65px; height: 66px;" src="https://media.discordapp.net/attachments/629369600269877248/640544627019218949/kakashi.png" alt="" /></span></address>
<p style="text-align: center;"><span style="font-size: small;"><strong><strong><img class="emoji" src="https://discordapp.com/assets/df0fba917be2ad5fc7939019465de627.svg" alt=":round_pushpin:" width="17" height="17" />Kakashi&nbsp;<img class="emoji" src="https://discordapp.com/assets/c6b26ba81f44b0c43697852e1e1d1420.svg" alt=":white_check_mark:" width="16" height="16" /></strong></strong></span></p>
<address style="text-align: center;"><span style="font-size: small;">auto 250 listas 'Combo Kakashi' | isattacking say Hakkojin | isattacking say Raijin Kirikunai | isattacking say Kamui | isattacking say Suiton Suikodan no Jutsu</span></address><address style="text-align: center;">&nbsp;</address><address style="text-align: center;"><span style="font-size: small;"><img style="width: 65px; height: 66px;" src="https://media.discordapp.net/attachments/629369600269877248/640544666541883405/madara.png" alt="" /></span></address>
<p style="text-align: center;"><span style="font-size: small;"><strong><strong><img class="emoji" src="https://discordapp.com/assets/df0fba917be2ad5fc7939019465de627.svg" alt=":round_pushpin:" width="17" height="17" />Madara&nbsp;<img class="emoji" src="https://discordapp.com/assets/c6b26ba81f44b0c43697852e1e1d1420.svg" alt=":white_check_mark:" width="16" height="16" /></strong></strong></span></p>
<address style="text-align: center;"><span style="font-size: small;">auto 250 listas 'Combo Madara' | isattacking say Gudodama | isattacking say Katon Ryuen Hoka | isattacking say Katon Goka Senpu | isattacking say Mokuton Hako Mokuryuy</span></address>
<p style="text-align: center;"><span style="font-size: small;">&nbsp;</span></p>